/**
 * Response Display Component
 *
 * Displays the generated response from a single model.
 * Shows:
 * - Generated text
 * - Model used
 * - Generation metadata (tokens, time)
 */

import React from 'react';

function ResponseDisplay({ response }) {
  return (
    <div className="bg-white rounded-lg shadow-md overflow-hidden">
      {/* Header with model info */}
      <div className="bg-gradient-to-r from-orange-50 to-orange-100 px-6 py-4 border-b border-orange-200">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-semibold text-gray-800">Response</h3>
            <p className="text-sm text-gray-600">
              Generated by: <span className="font-medium">{response.model_used}</span>
            </p>
          </div>
          {response.generation_time && (
            <div className="text-right">
              <p className="text-xs text-gray-500">
                ⚡ {response.generation_time.toFixed(2)}s
              </p>
              {response.tokens_generated && (
                <p className="text-xs text-gray-500">
                  📝 {response.tokens_generated} tokens
                </p>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Response content */}
      <div className="p-6">
        <div className="prose max-w-none">
          <p className="text-gray-800 whitespace-pre-wrap leading-relaxed">
            {response.text}
          </p>
        </div>
      </div>
    </div>
  );
}

export default ResponseDisplay;
